#!/usr/bin/env python3
"""Regenerate the UK data bundles from the parent BiCRS Atlas repo.

The UK Atlas is the United Kingdom subset of Frontier's BiCRS Atlas Europe
scope (https://github.com/hausfath/biomass_map). This script filters the
parent's built EU artifacts down to UK records and renames the window
globals EU_* -> UK_* (GEO_EU_* -> GEO_UK_*). Outputs are committed, so the
map works standalone; re-run only to refresh from an updated parent.

Usage:  python3 scripts/build_uk_from_parent.py "/path/to/parent/BiCRS Map"
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PARENT = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(HERE), "BiCRS Map")


def read_js_globals(path):
    """Parse a bundle of `window.NAME = <json>;` statements into a dict."""
    txt = open(path).read()
    out = {}
    for m in re.finditer(r"window\.([A-Z_0-9]+)\s*=\s*", txt):
        start = m.end()
        # value runs to the ';' that precedes the next `window.` assignment (or EOF)
        nxt = txt.find("window.", start)
        end = nxt if nxt != -1 else len(txt)
        val = txt[start:end].strip().rstrip("\n").strip()
        val = val.rstrip(";").strip().rstrip(";")
        # strip trailing line comments between statements
        val = re.sub(r"//[^\n]*$", "", val).strip().rstrip(";").strip()
        out[m.group(1)] = json.loads(val)
    return out


def write_js(path, header, pairs):
    with open(path, "w") as f:
        f.write("// " + header + "\n")
        f.write("// Auto-generated by scripts/build_uk_from_parent.py — do not edit by hand.\n")
        for name, val in pairs:
            f.write("window.%s = %s;\n" % (name, json.dumps(val, separators=(",", ":"))))


def main():
    src = os.path.join(PARENT, "src")
    geo = os.path.join(PARENT, "data", "geo")
    for p in (src, geo):
        if not os.path.isdir(p):
            sys.exit("Parent repo not found at %r — pass its path as the first argument." % PARENT)

    # ---- NUTS-2 geometry: keep UK regions only ----
    nuts = read_js_globals(os.path.join(geo, "geometry_eu_nuts.js"))["GEO_EU_NUTS"]
    nuts["features"] = [f for f in nuts["features"] if f["properties"].get("cntr") == "UK"]
    write_js(os.path.join(HERE, "data", "geometry_uk_nuts.js"),
             "UK NUTS-2 (ITL-2) geometry — Eurostat GISCO 2021 (20M), UK subset.",
             [("GEO_UK_NUTS", nuts)])
    print("UK NUTS-2 regions:", len(nuts["features"]))

    # ---- Storage-formation polygons: UK units only (CO2StoP) ----
    storage = read_js_globals(os.path.join(geo, "geometry_eu_storage.js"))["GEO_EU_STORAGE"]
    storage["features"] = [f for f in storage["features"]
                           if f["properties"].get("country") == "United Kingdom"]
    write_js(os.path.join(HERE, "data", "geometry_uk_storage.js"),
             "UK CO2 storage-unit polygons — JRC CO2StoP, UK subset.",
             [("GEO_UK_STORAGE", storage)])
    print("UK storage formations:", len(storage["features"]))

    # ---- Data bundle: filter each EU global to UK records ----
    eu = read_js_globals(os.path.join(src, "data_bundle_eu.js"))
    feeds = [r for r in eu["EU_FEEDSTOCKS"] if r.get("cntr") == "UK"]
    recs = [r for r in eu["EU_RECOMMENDATIONS"] if r.get("cntr") == "UK"]
    facs = [f for f in eu["EU_FACILITIES"] if f.get("country") == "GBR"]
    wwtps = [w for w in eu["EU_WWTPS"] if w.get("country") == "UK"]
    transport = {k: v for k, v in eu["EU_TRANSPORT"].items() if k.startswith("EU-UK")}
    # Storage projects: UK projects, plus any non-UK project a UK region actually
    # routes to (e.g. Porthos, Sleipner) so detail panels stay consistent.
    dests = {r.get("transport_dest_well") for r in recs} | {t.get("dest_well") for t in transport.values()}
    projects = [p for p in eu["EU_STORAGE_PROJECTS"]
                if p.get("country") == "GBR" or p.get("name") in dests]

    write_js(os.path.join(HERE, "src", "data_bundle_uk.js"),
             "UK data bundle — UK subset of the BiCRS Atlas EU NUTS-2 scope.",
             [("UK_FEEDSTOCKS", feeds),
              ("UK_RECOMMENDATIONS", recs),
              ("UK_FACILITIES", facs),
              ("UK_STORAGE_PROJECTS", projects),
              ("UK_TRANSPORT", transport),
              ("UK_WWTPS", wwtps),
              ("UK_PATHWAY_PROFILE", eu["EU_PATHWAY_PROFILE"])])
    print("feedstocks:", len(feeds), "| recs:", len(recs), "| facilities:", len(facs),
          "| projects:", len(projects), "| transport:", len(transport), "| wwtps:", len(wwtps))
    tot = sum(r.get("cdr_potential_mtpa") or 0 for r in recs)
    print("UK CDR potential: %.1f Mt CO2/yr" % tot)


if __name__ == "__main__":
    main()
